### PR TITLE
Viacoin: Add viaatomic swap

### PR DESCRIPTION
**Pull request by romanornr**
Pull request for adding Viacoin. 

9787943acc6c217953905b9c1d3e35a2

### CODE REVIEW

**Comment by jrick** [comment]
I'll get to reviewing this soon but off the bat I'm noticing that you didn't add any of your dependencies to the dep manifest (Gopkg.toml).  We'll need those added (and Gopkg.lock updated) to pin down the dependency repos to specific commits for security and reliability.  https://github.com/golang/dep

Does viacoin have a running testnet chain?

**Comment by romanornr** [comment]
I just added the commits for the dep manifest to pin down the deps with the specific commit.
Viacoin does not have a testnet chain running atm.

**Comment by jrick** [comment]
I'll try to give this another look soon, but it will need to be switched over to use OP_SHA256 instead of OP_RIPEMD160 since we just converted the rest of the tools.

Also since there is no testnet to test this with, and I don't have any mainnet viacoin, could you show the output of a "one sided" atomic swap?  It's fine to do it with a single wallet (tools don't care which wallet ends up creating the redemption).

**Comment by romanornr** [comment]
Alright I will. I also see you reverted that commit later. 
Should I wait instead?

Meanwhile I will get the testnet working again. 
(I took over the Viacoin project solo, so sometimes it takes some extra time to contact the original owner & get a reply back on important questions) 

Anyways thanks for contacting me back.

**Comment by jrick** [comment]
it was reverted due to a bug, i'm waiting on vertcoin to pull in the required change, but if it takes too long then i'll just point dep at my fork instead so we can keep the ball rolling. see #40.  if you can get testnet up quickly and get this tested then it can go in as is, otherwise if the SHA256 change happens then i'll let you know

**Comment by romanornr** [comment]
Testnet is up.

viacoin.conf 
````
testnet=1
rpcuser=rpcuser
rpcpassword=rpcpass
listen=1
addnode=159.203.109.115
addnode=159.203.109.115
addnode=104.131.34.150
addnode=104.131.34.150
````

**Comment by jrick** [comment]
Thanks! The (fixed) SHA256 change just landed as well, so please update this PR for that.

**Comment by romanornr** [comment]
Updated my PR. Waiting for Travis CI to be completed.

**Comment by romanornr** [comment]
I will try an atomic swap on testnet first. Just to be sure. I will update you about it.

**Comment by romanornr** [comment]
Yep, An atomic swap for Viacoin-Litecoin on testnet worked out.
I think it works all fine now.

If you need Viacoin testnet coins, let me know.

**Comment by jrick** [comment]
Cool, I'll give it a try.  Send some coins to tFaR9R2vGnR5R4ETprVzfCiFn97j9hMhYV.

Also it appears that no testnet blocks have been created since 7aa7226d5c292ad66e5c65263be161435da9c86471328af4fc35e6eeb4fb794a (height 4289) which was mined about 4 days ago.

**Comment by romanornr** [comment]
hmm the port issue is strange. Trying to grep -R "

**Comment by jrick** [comment]
I figured out the redemption error, it was my fault.  I created two contracts initially and used the wrong secret.

**Comment by romanornr** [comment]
Awesome. Give me a minute, I will fix those strings and portnumber.

**Comment by romanornr** [comment]
Done & all checks passed. 

For fixing the strings: https://github.com/viacoin/viautil/commit/0f6849edd51cb0e1e88cf31a92b7e7e492d79030

**Comment by romanornr** [comment]
Alright, I think I can. I made a test branch so you can see how that looks like.
(I think this is what you mean)
https://github.com/viacoin/atomicswap/commits/dev

If that looks good to you, I will apply it to the master branch.

**Comment by jrick** [comment]
Yep that's right, you can just force push that to replace your master branch on your fork to update this pr.

**Comment by romanornr** [comment]
Done !

**Comment by jrick** [comment]
Well i spoke too soon, master was more recently updated and so this needs another rebase.

I also noticed that running dep ensure modifies the lockfile with a new inputs digest, so please re-run that and squash that in as well.

**Comment by jrick** [comment]
did you rerun dep ensure?

**Comment by romanornr** [comment]
I did not yet, it fails on me.

````
romano@arch ~/go/src/atomicswap                                      [19:57:27] 
> $ dep ensure                                                      [±master ✓]
^CSignal received: waiting for 1 ops to complete...
panic: canary - shouldn't be possible this SourceMgr has been released, its methods can no longer be called

goroutine 1 [running]:
github.com/golang/dep/internal/gps.(*solver).unselectLast(0xc4202ac000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/yaourt-tmp-romano/aur-dep/src/src/github.com/golang/dep/internal/gps/solver.go:1281 +0x70c
github.com/golang/dep/internal/gps.(*solver).backtrack(0xc4202ac000, 0xc4201bb1a0)
	/tmp/yaourt-tmp-romano/aur-dep/src/src/github.com/golang/dep/internal/gps/solver.go:1036 +0x3aa
github.com/golang/dep/internal/gps.(*solver).solve(0xc4202ac000, 0x0, 0x0, 0xc420595760)
	/tmp/yaourt-tmp-romano/aur-dep/src/src/github.com/golang/dep/internal/gps/solver.go:495 +0x79f
github.com/golang/dep/internal/gps.(*solver).Solve(0xc4202ac000, 0x20, 0x20, 0xc4200189e0, 0x20)
	/tmp/yaourt-tmp-romano/aur-dep/src/src/github.com/golang/dep/internal/gps/solver.go:440 +0xaa
main.(*ensureCommand).runDefault(0xc420175796, 0xc420098fa0, 0xc42008a020, 0x0, 0x0, 0xc42009b380, 0xb6f9c0, 0xc4203201e0, 0xc420014004, 0x1e, ...)
	/tmp/yaourt-tmp-romano/aur-dep/src/src/github.com/golang/dep/cmd/dep/ensure.go:280 +0x150
main.(*ensureCommand).Run(0xc420175796, 0xc420098fa0, 0xc42008a020, 0x0, 0x0, 0x0, 0x0)
	/tmp/yaourt-tmp-romano/aur-dep/src/src/github.com/golang/dep/cmd/dep/ensure.go:205 +0x4f4
main.(*Config).Run(0xc42007cf00, 0xc42007cf00)
	/tmp/yaourt-tmp-romano/aur-dep/src/src/github.com/golang/dep/cmd/dep/main.go:160 +0x7f6
main.main()
	/tmp/yaourt-tmp-romano/aur-dep/src/src/github.com/golang/dep/cmd/dep/main.go:45 +0x1fc
````

**Comment by jrick** [comment]
Alright i'll fix it up on master after then

**Pull request merged**
