### PR TITLE
Add links to first DCR-BTC mainnet swap.

### PR DESCRIPTION
**Pull request by realingsoc**
Credit goes to Narcélio Filho (@narcelio).

### CODE REVIEW

**Comment by jrick** [comment]
I think if we start adding all of these then they should be put in their own section or maybe their own page.  It's certainly cool but takes away from the educational aspect of the readme.

**Comment by realingsoc** [comment]
Should we create a wiki here instead? Might be a better place for the txids if we're going to accumulate a few from additions. I imagine you'd keep the DCR <> LTC link in README.md since that's been linked to extensively and adheres to the educational aspect of the document (as a real example of a swap).

**Comment by jrick** [comment]
I was thinking wiki as well.  Only concern would be breaking the links in @coblee's tweet.

**Comment by realingsoc** [comment]
Probably best to leave the DCR <> LTC section as-is in that case and duplicate it in the wiki. As a single real-world example, I don't think it looks out of place.

**Comment by jrick** [comment]
Makes sense.  Closing this PR then and we can get some other notable swaps added to a wiki page.

**Pull request closed without merging**
