### PR TITLE
Fix signrawtransaction not found error

### LINKED ISSUE #105: [btcamoticswap] deprecated signrawtransaction command
If running btcatomicswap with bitcoin core and, bitcoin core on master, we will receive the following error message: 

```
signrawtransaction: -32: signrawtransaction was removed in v0.18.
Clients should transition to using signrawtransactionwithkey and signrawtransactionwithwallet
```
When trying to do an atomic swap, as signrawtransaction is deprecated.

### PR DESCRIPTION
**Pull request by vctt94**
fixes #105 

needs: https://github.com/btcsuite/btcd/pull/1413 and https://github.com/btcsuite/btcd/pull/1415

### CODE REVIEW

**Comment by jrick** [comment]
Thanks for this

In case it takes too long for the btcd PRs to be merged, you can still call the RPC through the use of the raw APIs.  We already do this for fundrawtransaction.

https://github.com/decred/atomicswap/blob/532f01ef64588676cc214b413a0da63f81590b8d/cmd/btcatomicswap/main.go#L406

**Comment by vctt94** [comment]
Should I add the raw commands to the API into this PR?

**Comment by imestin** [comment]
What is the situation with this pull request?
I would like to create a test transaction. Should I wait for this pull request, or should I try to fix it with some temporary solution?

**Comment by vctt94** [comment]
Not sure if this PR is updated with the current btcd repo. But you can use https://github.com/decred/atomicswap/pull/111 which calls the request by raw request as @jrick  suggested.

**Comment by imestin** [comment]
thank you! it worked.

**Comment by jrick** [comment]
Obsoleted by #111.

**Pull request closed without merging**
