### PR TITLE
Monacoin support

### PR DESCRIPTION
**Pull request by wakiyamap**
testnet4(monacoin is testnet ver4) case
https://gist.github.com/wakiyamap/137703f07311e0af70231e875485c96f

mainnet case
https://gist.github.com/wakiyamap/e51bf1a028fe12c72a02e48d01835db5

### CODE REVIEW

**Comment by jrick** [comment]
Nice job with the port.  After a quick glance, it looks like some amounts are still being formatted as BTC though.  To fix that, change the String method for AmountUnit (https://github.com/wakiyamap/monautil/blob/master/amount.go#L33).

I'm going to finish reviewing all of the other ports with open pull requests first before I take a closer look, but should be able to get to this soon.  You will need to rebase this over those once they have been merged since there will be conflicts with the Gopkg.lock, and I'll let you know when you can do that.

**Comment by wakiyamap** [comment]
@jrick Thanks!!  I fix it.

**Comment by wakiyamap** [comment]
@jrick thanks!! I fix it and rebase.

**Comment by jrick** [comment]
This is reviewed and ready except for the Gopkg.toml/lock conflicts.

**Comment by wakiyamap** [comment]
I misunderstood about rebase. thanks

**Pull request merged**
