### PR TITLE
Added Actinium (ACM) support

### PR DESCRIPTION
**Pull request by brakmic**
Hi,

This PR adds atomic swaps for Actinium (ACM).

A few resources regarding our project:

HP: https://actinium.org
GitHub: https://github.com/Actinium-project
ANN: https://bitcointalk.org/index.php?topic=4300440
Explorer: https://explorer.actinium.org
Explorer2: https://explorer2.actinium.org
Testnet Explorer: https://test-explorer.actinium.org

I have tested the functionality by using **acmatomicswaps** and **btcatomicswaps**. 

Here the results in chronological order:

BTC **initiate** txn: https://test-insight.bitpay.com/tx/970876d6bbafc6bcb6e2af76c48af390bdf7dc0ef3fd73e40e4303d923c6c305

ACM **participate** txn: https://test-explorer.actinium.org/tx/8b5af3b2e6bc7c2f7d8635384ca9d7afc16659a7378b8c76ab80a5c8802be21d

BTC **redeem** txn: https://test-insight.bitpay.com/tx/f0be32fb27d5ff8b49936337d18b9321d735ecc03b5db4fc6417abcbffb34ede

ACM **redeem** txn: https://test-explorer.actinium.org/tx/e0a6a53069aaef3bd7c4577bf11e4d9ca7b39e85524e65cd61453bac16ede4a8

*One hint*: the examples in your README seem to have been written for an older variant of atomicswaps because the *redeem* & *extractsecret* calls are missing the *secret hash* respective *secret* value parameters.

Kind regards,

### CODE REVIEW

**Comment by dajohi** [comment]
@brakmic please rebase  now that go 1.11+ is required.

**Comment by brakmic** [comment]
> @brakmic please rebase now that go 1.11+ is required.

Rebase done. Removed Gopkg.lock.

**Comment by dajohi** [comment]
@brakmic need to add go.mod and go.sum in cmd/acmatomicswap/

https://github.com/golang/go/wiki/Modules

**Comment by brakmic** [comment]
> @brakmic need to add go.mod and go.sum in cmd/acmatomicswap/
> 
> https://github.com/golang/go/wiki/Modules

Have moved them to acmatomicswap.

**Comment by dajohi** [comment]
@brakmic travis-ci has you flagged for abuse.  You can email support@travis-ci.com and ask to have the ban removed.

**Comment by brakmic** [comment]
> @brakmic travis-ci has you flagged for abuse. You can email [support@travis-ci.com](mailto:support@travis-ci.com) and ask to have the ban removed.

Weird. Will do it.

**Comment by brakmic** [comment]
@dajohi 

I got the email from travis. They can't find any misuse flag. Could your please, give me a screenshot of the misuse flag. 

Here the content of their email:

```text
 Juz (Travis CI)

Feb 21, 11:27 EST

Hi there Harris,

Thanks for getting in touch and I'm sorry for the frustration!

I"m having some difficulty finding any misuse flag for either decred or brakmic.
Could you send a screenshot of the misuse flag?

Many thanks and looking forward to hearing from you!
Cheers,
Juz
```

**Comment by brakmic** [comment]
@dajohi 

I got another email from Travis CI team:

```text
Hi Harris, I'll close this ticket for now but please don't hesitate to follow up here if there are any issues. As my colleague confirmed, we don't see any misuse flag for account brakmic. We'd be happy to assist further if you have any questions, concerns or require further assistance.
```

They see no abuse in their systems, so I don't understand where the problem is. I have also logged on in my Travis-account today and couldn't see any warning there.

**Comment by dajohi** [comment]
```
 # master 555117a
6 days ago
added go.mod & go.sum to acmatomicswap
-
Abuse detected 
```

point them to https://github.com/decred/atomicswap/commit/555117a perhaps.

**Comment by brakmic** [comment]
Ok, will do it.

**Comment by brakmic** [comment]
@dajohi 

I got a question from Travis team. It's about one of your team's projects:

```
Hello Brakmic,

Thanks for providing additional information, we are working to get this resolved as soon as possible.
By any chance, can you (or one of the Decred team members) shed some light on the 

https://github.com/decred/dcrseeder project? 

Our systems appear to be flagging this organization due to some code in this repo.

I look forward to hear from you and we will take it from there.

Regards
```

**Comment by dajohi** [comment]
I sent an email to travis-ci.  will post once I receive a response.

**Comment by brakmic** [comment]
@dajohi 

The Travis team has unflagged my account. I have sent two trivial changes just to activate the build procedures and it worked. Here their email:

```
Hello Harris,

I see your builds are now successful. I'll be marking this as SOLVED.

If you run into any more issues, feel free to reach out to us.

Thanks and Happy Building!
```

**Pull request closed without merging**
